#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

#include "keymap_german.h"
#include "sendstring_german.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

//clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(
        KC_TAB,        DE_Q, DE_W, DE_E, DE_R, DE_T,      DE_Z, DE_U, DE_I,    DE_O,   DE_P,    KC_BSPC,
        CTL_T(KC_ESC), DE_A, DE_S, DE_D, DE_F, DE_G,      DE_H, DE_J, DE_K,    DE_L,   DE_ODIA, DE_ADIA,
        KC_LSFT,       DE_Y, DE_X, DE_C, DE_V, DE_B,      DE_N, DE_M, DE_COMM, DE_DOT, DE_MINS, DE_UDIA,
                            KC_LGUI, MO(1), KC_ENT,      KC_SPC, MO(2), KC_RALT
        ),  
    [1] = LAYOUT_split_3x6_3(
        DE_CIRC,  DE_1,     DE_2,      DE_3,    DE_4,    DE_5,       DE_6,    DE_7,    DE_8,    DE_9,    DE_0,    KC_BSPC,
        KC_LCTL,  KC_NO,    KC_HOME,   KC_UP,   KC_END,  KC_NO,      KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, KC_NO,   DE_SS, 
        KC_LSFT,  KC_PSCR,  KC_LEFT,   KC_DOWN, KC_RGHT, KC_NO,      DE_LABK, DE_ASTR, DE_PLUS, DE_RABK, KC_NO, DE_TILD,
                                    KC_LGUI, KC_TRNS,   KC_ENT,      KC_SPC, MO(3), KC_RALT
        ),
    [2] = LAYOUT_split_3x6_3(
        DE_DEG,  DE_EXLM, DE_DQUO, DE_SECT, DE_DLR, DE_PERC,    DE_AMPR, DE_SLSH, DE_LPRN, DE_RPRN, DE_EQL, KC_BSPC,
        KC_LCTL, DE_SUP2, DE_SUP3, KC_NO,   KC_NO,  KC_NO,      DE_GRV,  DE_LCBR, DE_LBRC, DE_RBRC, DE_RCBR, DE_BSLS,
        KC_LSFT, KC_NO,   KC_NO,   KC_NO,   KC_NO,  KC_NO,      DE_PIPE, DE_ASTR, DE_PLUS, DE_HASH, DE_QUOT, DE_TILD,
                                    KC_LGUI, MO(3), KC_ENT,     KC_SPC,  KC_TRNS, KC_RALT
        ),
    [3] = LAYOUT_split_3x6_3(
        KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5, KC_F6,   KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12,
        RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI, KC_NO, KC_NO,   KC_NO, KC_NO, KC_NO, KC_NO,  KC_NO,  KC_NO,
        RGB_MOD, RGB_HUD, RGB_SAD, RGB_VAD, KC_NO, KC_NO,   KC_NO, KC_NO, KC_NO, KC_NO,  KC_NO,  QK_BOOT,
                                KC_LGUI, KC_TRNS, KC_ENT,   KC_SPC, KC_TRNS, KC_RALT
        )
};

//clang-format on
#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE
//  